# Generated by Django 4.1.5 on 2023-01-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=200)),
                ('last_Name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('LATAM', 'LTM'), ('UNITED STATES OF AMERICA', 'USA'), ('CANADA', 'CANADA')], max_length=60)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
