# Generated by Django 4.1.5 on 2023-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_infousers_delete_infouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='constructoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=200)),
                ('password_c', models.CharField(max_length=200)),
                ('email_c', models.CharField(max_length=250)),
                ('text_c', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.URLField()),
                ('nombre_img', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(max_length=100)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('materiales', models.CharField(max_length=250)),
                ('presupuesto_prom', models.CharField(max_length=1000)),
                ('contactos', models.TextField(max_length=400)),
                ('fecha_max', models.DateField()),
            ],
        ),
    ]
