# Generated by Django 4.1.5 on 2023-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_constructoras_imgs_materiales_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='fecha_max',
        ),
        migrations.AlterField(
            model_name='posts',
            name='contactos',
            field=models.CharField(max_length=400),
        ),
    ]
