# Generated by Django 4.1.5 on 2023-02-04 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_remove_posts_fecha_max_alter_posts_contactos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='contactos',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='materiales',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='presupuesto_prom',
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
