# Generated by Django 4.1.5 on 2023-02-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_posts_contactos_remove_posts_materiales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/%y/%m/%d/')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
