# Generated by Django 4.1.5 on 2023-02-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='pics/', upload_to='pics/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
