# Generated by Django 4.1.5 on 2023-02-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_posts_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='materiales',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_post_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
