# Generated by Django 4.1.5 on 2023-02-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_posts_options_alter_materiales_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='materiales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.materiales'),
        ),
    ]
