# Generated by Django 4.1.5 on 2023-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_posts_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='materiales',
        ),
        migrations.AddField(
            model_name='posts',
            name='materiales',
            field=models.ManyToManyField(null=True, to='tasks.materiales'),
        ),
    ]
