# Generated by Django 4.1.5 on 2023-02-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_posts_materiales_posts_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='materiales',
        ),
        migrations.AddField(
            model_name='posts',
            name='materiales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.materiales'),
        ),
    ]
