# Generated by Django 4.1.5 on 2023-02-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_posts_materiales_posts_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='materiales',
        ),
    ]
