# Generated by Django 4.1.5 on 2023-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_posts_materiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('photo', models.URLField(max_length=250)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
