# Generated by Django 4.1.5 on 2023-02-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_openai'),
    ]

    operations = [
        migrations.AddField(
            model_name='openai',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OpenAI_owner_img', to=settings.AUTH_USER_MODEL),
        ),
    ]
