# Generated by Django 4.1.5 on 2023-02-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_openai_options_posts_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='fecha_prom',
        ),
    ]
